### ISSUE TITLE
Error in Vignettes

### ISSUE THREAD

**Issue by snvv** [anthonydevaux/DynForest#12]
Hello
In the example "How to use DynForest with continuous outcome?" the return of the function

```markdown
res_dyn <- DynForest(
  timeData = timeData_train, 
  fixedData = fixedData_train,
  timeVar = "time", 
  idVar = "id", 
  timeVarModel = timeVarModel,
  mtry = 10,
  Y = Y, 
  seed = 1234
)
```

is 

```r
Error in checking(timeData = timeData, fixedData = fixedData, idVar = idVar,  : 
  'timeData' predictor names should be included in the list names of 'timeVarModel'!
```

**Comment by anthonydevaux** [comment]
Hi @snvv 

Thank you for raising this issue. Indeed, I forgot to define the marker names in the `timeVarModel` list object. Please add the following code before executing DynForest function:
`names(timeVarModel) <- paste0("marker",seq(6))`

The vignettes have been written with an old DynForest version, and might be out-of-date. Until I update them, please refer to the preprint https://arxiv.org/pdf/2302.02670 for the most up-to-date examples.

Best,
Anthony
