### ISSUE TITLE
Question: 

### ISSUE THREAD

**Issue by instantkaffee** [anthonydevaux/DynForest#13]
Thx for the package.
I have a question.
In your example code you show definition of timevarmodel using linear model.
I‘d be interested to use gam spline, even shape contrained ones (like monotonic from  scam).
Is this feasible?
Thx for your response.

**Comment by anthonydevaux** [comment]
Hi @instantkaffee,

The current implementation of `DynForest` only allows linear mixed models. However, smoother functions using splines can be included in the formula when you define the trajectory of your time-dependent predictors. 

See below an example with nature splines (using `ns()` function from `splines` package) with knots defined at `time = 5` and `time = 10`:

```
timeVarModel <- list(serBilir = list(
  fixed = serBilir ~ splines::ns(time, knots = c(5,10)),
  random = ~ splines::ns(time, knots = c(5,10)))
)
```

Best,
Anthony
