### ISSUE TITLE
Error when running DynForest function

### ISSUE THREAD

**Issue by jmanacup** [anthonydevaux/DynForest#2]
Good day,

I stumbled upon this [vignette](https://cran.r-project.org/web/packages/DynForest/vignettes/DynForest_surv.html) and was following the guide and after encountering and running the `DynForest` function, it stops a fourth of the way and throws an error,

`Error in checkForRemoteErrors(val) : 
  one node produced an error: the leading minor of order 2 is not positive definite`

Here is the code that I used which is the same as the one provided in the vignette:

    library(DynForest)
    data(pbc2)
    
    set.seed(1234)

    id <- unique(pbc2$id)
    id_sample <- sample(id, length(id)*2/3)
    id_row <- which(pbc2$id%in%id_sample)

    pbc2_train <- pbc2[id_row,]
    pbc2_pred <- pbc2[-id_row,]

    timeData_train <- pbc2_train[,c("id","time",
                                "serBilir","SGOT",
                                "albumin","alkaline")]

    fixedData_train <- unique(pbc2_train[,c("id","age","drug","sex")])

    timeVarModel <- list(serBilir = list(fixed = serBilir ~ time,
                                     random = ~ time),
                     SGOT = list(fixed = SGOT ~ time + I(time^2),
                                 random = ~ time + I(time^2)),
                     albumin = list(fixed = albumin ~ time,
                                    random = ~ time),
                     alkaline = list(fixed = alkaline ~ time,
                                     random = ~ time))

    Y <- list(type = "surv",
          Y = unique(pbc2_train[,c("id","years","event")]))

    res_dyn <- DynForest(timeData = timeData_train, fixedData = fixedData_train,
                     timeVar = "time", idVar = "id", timeVarModel = timeVarModel,
                     ntree = 200, nodesize = 5, minsplit = 5, cause = 2,
                     Y = Y, seed = 1234)

I  was just wondering if this is just happening in my machine or is it a package-related issue. Thanks!

**Comment by anthonydevaux** [comment]
Hi John,

Thank you for your feedback about this issue. As you suggested, I've also found the same issue on my machine. This error might occur during the estimation of the longitudinal predictors with large values. Therefore, I advise transforming them using a log (for instance) to also ensure normality assumption in the estimation process.
`pbc2$serBilir <- log(pbc2$serBilir)`
`pbc2$SGOT <- log(pbc2$SGOT)`
`pbc2$albumin <- log(pbc2$albumin)`
`pbc2$alkaline <- log(pbc2$alkaline)`

The new version (1.1.0) of DynForest is also available on my GitHub (and soon on CRAN) to fix those bugs among others. Feel free to use it!

Anthony
