### ISSUE TITLE
Problem about the function compute_VIMP

### ISSUE THREAD

**Issue by ChenXinaha** [anthonydevaux/DynForest#3]
in the line 93, Inputs <- names(rf$Inputs) should be changed as "Inputs <- names(rf$Inputs[!sapply(rf$Inputs,is.null)])" because there may be Null in the elements of Inputs (Longitudinal, Numeric and Factor)

**Comment by anthonydevaux** [comment]
Hi @ChenXinaha.

Thank you for your comment. As you suggested, I fixed the bug with Inputs object in compute_VIMP() function. The same issue was also present in compute_gVIMP() function and therefore fixed.

I've just uploaded a new version of DynForest on GitHub without these bugs.

Best regards,

Anthony
