### ISSUE TITLE
Parameter cause in function DynForest

### ISSUE THREAD

**Issue by CathLab21** [anthonydevaux/DynForest#5]
Hi!
Concerning the DynForest function, it seems to me that the "cause"  parameter  does not work correctly in the case  cause=1 (tried now with the new version of the package).

The code example with pbc2 uses cause=2. In the attached  file, I  added 2 lines  to this example to recode the event of interest by 1 and thus put cause =1. It doesn't work on my PC, the error message is :
"Error in checkForRemoteErrors(val) : 
  2 nodes produced errors; first error: longueur de 'row.names' incorrecte"

Thanks a lot for sharing your package and  detailed examples!

[codeDynForest2.txt](https://github.com/anthonydevaux/DynForest/files/10101688/codeDynForest2.txt)

**Comment by anthonydevaux** [comment]
Hi @CathLab21,

This bug should not occur, I fixed it last week. However, to be sure, did you try with the new version on GitHub (and not the current one on CRAN) using `devtools::install_github("anthonydevaux/DynForest")` ?
On my computer, I don't have any error with your example using R version 4.2.2. I don't know if the R version might also be a problem.

Let me know if you still have this issue.

Best,

Anthony

**Comment by CathLab21** [comment]
Thanks for the quick answer! You're right :  it works with the new version for the pbc2 example.  But not for mine.
I think the problem is the variable "time". If we give it another name (for instance "temps"), it doesn't work anymore.
Look at the modified pbc2 example (time is changed by temps in the joined file: the error on my PC is:

 Error in checkForRemoteErrors(val) : 
  2 nodes produced errors; first error: colonnes non définies sélectionnées

Best,
Catherine
 
[codeDynForest3.txt](https://github.com/anthonydevaux/DynForest/files/10104179/codeDynForest3.txt)

**Comment by anthonydevaux** [comment]
Hi @CathLab21,

I have just fixed this issue in the new GitHub version. Now you can use another name for the time variable.

Let me know if you find other bugs.

Best,
Anthony

**Comment by CathLab21** [comment]
Ok I will try,

Thanks !

 

De : Anthony Devaux ***@***.*** 
Envoyé : lundi 5 décembre 2022 13:30
À : anthonydevaux/DynForest ***@***.***>
Cc : CathLab21 ***@***.***>; Mention ***@***.***>
Objet : Re: [anthonydevaux/DynForest] Parameter cause in function DynForest (Issue #5)

 

Hi @CathLab21 <https://github.com/CathLab21> ,

I have just fixed this issue in the new GitHub version. Now you can use another name for the time variable.

Let me know if you find other bugs.

Best,
Anthony
