### ISSUE TITLE
question about var_split_surv.R

### ISSUE THREAD

**Issue by ChenXinaha** [anthonydevaux/DynForest#6]
I think it may be appropriate not to rename the variable name in the follwing code: 

      colnames(data_model)[which(colnames(data_model)=="time")] <- timeVar

**Comment by anthonydevaux** [comment]
Hi @ChenXinaha,

I had an issue when the time name variable was different than `time`. That's why I should have to rename this variable. Could you tell me why you think this rename is not appropriate? Does the rename lead to other bugs in related functions?

Best,
Anthony

**Comment by ChenXinaha** [comment]
If you rename the time name variable in the data_model, you need to have the same time variable name in the timeVarModel (as the following example) or say the mixed model.


timeVarModel <- list(serBilir = list(fixed = serBilir ~ time,
                                      random = ~ time),
                      SGOT = list(fixed = SGOT ~ time + I(time^2),
                                 random = ~ time + I(time^2)),
                      albumin = list(fixed = albumin ~ time,
                                    random = ~ time),
                     alkaline = list(fixed = alkaline ~ time,
                                      random = ~ time))

**Comment by ChenXinaha** [comment]
And in the function DynForest, there has been define the name of time variable in the Longitudinal  list:

Longitudinal <- list(type = "Longitudinal",
                         X = subset(timeData, select = -c(get(idVar), get(timeVar))),
                         id = timeData[,idVar],
                         time = timeData[,timeVar],
                         model = timeVarModel)

**Comment by ChenXinaha** [comment]
In my opinion, it just needs to ensure the name of time variable as "time" in the timeVarModel, and it is not important about the "timeVar".

**Comment by anthonydevaux** [comment]
I agree with you, but I think it can be easier for users that formula variables match with data variables in case of "time" variable does not exist.

**Comment by goncabuyrukoglu** [comment]
Dear Anthony,

Thank you very much for contributing such an amazing work. It is fabulous. 

I have accessed a dataset which has 14 longitudinal predictors along with survival times and event status. 
I am trying to fit the random forest model using DynForest() function.  Once the name of the time variable in the dataset and code itself,  which is  "Elapsed_years", I got the error : "Error in checkForRemoteErrors(val) : 
  3 nodes produced errors; first error: undefined columns selected". 
When I rename the time variable as "time" and the rest of everything is the same, I got the error : "Error in checkForRemoteErrors(val) : 
  3 nodes produced errors; first error: invalid 'row.names' length".  I tried many things to get rid of the error; however nothing works. Do you have an idea how to solve this problem. 

In addition to this,  I pooled the event as 0's and 1's and write cause=2, I got result in 2 seconds, which does not seem trustable. 

 This is the results that I got in 2 seconds with cause=2.

head(res_dyn$rf[,1]$V_split)
  type id_node var_split feature threshold  N Nevent depth
1 Leaf       1        NA      NA        NA 67      0     1


I would be appreciated if you can help to me.

Best regards, 
Gonca
